language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
before_script:
  - git clone --branch master https://github.com/lukexie/lukexie.github.io public
script:
  - npm run build
after_success:
  - cd public
  - git config user.name "lukexie@Travis" 
  - git config user.email "luke.xie@yahoo.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${DEPLOY_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - raw
env:
  global:
  - GH_REF: github.com/lukexie/lukexie.github.io.git
